//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimeOnex.ModelData.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentario
    {
        public int comentarioID { get; set; }
        public int usuarioID { get; set; }
        public int episodioID { get; set; }
        public string texto { get; set; }
        public Nullable<System.DateTime> dataComentario { get; set; }
    
        public virtual Episodio Episodio { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
