//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimeOnex.ModelData.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Episodio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Episodio()
        {
            this.Comentario = new HashSet<Comentario>();
        }
    
        public int episodioID { get; set; }
        public int animeID { get; set; }
        public string titulo { get; set; }
        public int vizualizacoes { get; set; }
        public int duracaoMin { get; set; }
        public int numeroDoEpisodio { get; set; }
        public string caminhoDoArquivo { get; set; }
    
        public virtual Anime Anime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comentario> Comentario { get; set; }
    }
}
