//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimeOnex.ModelData.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anime
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Anime()
        {
            this.Episodio = new HashSet<Episodio>();
        }
    
        public int animeID { get; set; }
        public string titulo { get; set; }
        public Nullable<System.DateTime> dataEstreia { get; set; }
        public Nullable<int> numeroDeTemporadas { get; set; }
        public Nullable<int> quantidadeDeEpisodios { get; set; }
        public string studio { get; set; }
        public string sinopse { get; set; }
        public string caminhoDaImagem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Episodio> Episodio { get; set; }
    }
}
